import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import Provider from './components/Provider'
import { authOptions } from './options'
import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Excommunicado',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}><Provider><NavBar sesh={session}></NavBar><div className="min-h-screen">{children}</div><Footer></Footer></Provider></body>
    </html>
  )
}
